[package]
name = "rust-getting-started"
version = "0.1.0"
authors = ["Stefano Giraldi <stefano.giraldi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
